spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8000
resilience4j:
  circuitbreaker:
    instances:
      sample-api:
        waitDurationInOpenState: 5s
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
        retryExceptions:
          - java.io.IOException
  ratelimiter:
    instances:
      sample-api-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      sample-api-bulkhead:
        maxConcurrentCalls: 2